//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileBook.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProfileBook.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Profile.
        /// </summary>
        public static string AddEditProfilePageTitle {
            get {
                return ResourceManager.GetString("AddEditProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a photo.
        /// </summary>
        public static string AddingPhotoAlert {
            get {
                return ResourceManager.GetString("AddingPhotoAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGNIN.
        /// </summary>
        public static string ButtonSignIn {
            get {
                return ResourceManager.GetString("ButtonSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGNUP.
        /// </summary>
        public static string ButtonSignUp {
            get {
                return ResourceManager.GetString("ButtonSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelAlert {
            get {
                return ResourceManager.GetString("CancelAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change theme.
        /// </summary>
        public static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm deletion?.
        /// </summary>
        public static string ConfirmDeleteAlert {
            get {
                return ResourceManager.GetString("ConfirmDeleteAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteAlert {
            get {
                return ResourceManager.GetString("DeleteAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Description&quot; field is too large, it must be no more than 120 characters.
        /// </summary>
        public static string DescrTooMoreAlert {
            get {
                return ResourceManager.GetString("DescrTooMoreAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Profile Collection:.
        /// </summary>
        public static string DisplayProfileCollection {
            get {
                return ResourceManager.GetString("DisplayProfileCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download from gallery.
        /// </summary>
        public static string DownFromGalleryAlert {
            get {
                return ResourceManager.GetString("DownFromGalleryAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields  &quot;Name&quot; and  &quot;Nickname&quot; must be filled.
        /// </summary>
        public static string EmptyfieldsAlert {
            get {
                return ResourceManager.GetString("EmptyfieldsAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Alert {
            get {
                return ResourceManager.GetString("Error_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect login.
        /// </summary>
        public static string IncorrectLoginAlert {
            get {
                return ResourceManager.GetString("IncorrectLoginAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login must not start with a number and login length must be no less than 4 characters and no more than 16 characters.
        /// </summary>
        public static string IncorrectLoginTextAlert {
            get {
                return ResourceManager.GetString("IncorrectLoginTextAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        public static string IncorrectPasswAlert {
            get {
                return ResourceManager.GetString("IncorrectPasswAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain from 8 to 16 characters and among which there must be a capital letter a small letter and also a number.
        /// </summary>
        public static string IncorrectPasswTextAlert {
            get {
                return ResourceManager.GetString("IncorrectPasswTextAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login or password.
        /// </summary>
        public static string InvalidLoginOrPasswAlert {
            get {
                return ResourceManager.GetString("InvalidLoginOrPasswAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGNUP.
        /// </summary>
        public static string LableHyperlinc {
            get {
                return ResourceManager.GetString("LableHyperlinc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profiles added.
        /// </summary>
        public static string LableMainList {
            get {
                return ResourceManager.GetString("LableMainList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This login is already registered.
        /// </summary>
        public static string LoginAlreadyRegistredAlert {
            get {
                return ResourceManager.GetString("LoginAlreadyRegistredAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main List.
        /// </summary>
        public static string MainListPageTitle {
            get {
                return ResourceManager.GetString("MainListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string MenuItemDelete {
            get {
                return ResourceManager.GetString("MenuItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        public static string MenuItemEdit {
            get {
                return ResourceManager.GetString("MenuItemEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkAlert {
            get {
                return ResourceManager.GetString("OkAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not confirmed.
        /// </summary>
        public static string PasswNotConfirmAlert {
            get {
                return ResourceManager.GetString("PasswNotConfirmAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PlaceholderDescription {
            get {
                return ResourceManager.GetString("PlaceholderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string PlaceholderLogin {
            get {
                return ResourceManager.GetString("PlaceholderLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PlaceholderName {
            get {
                return ResourceManager.GetString("PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickName.
        /// </summary>
        public static string PlaceholderNickName {
            get {
                return ResourceManager.GetString("PlaceholderNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PlaceholderPassword {
            get {
                return ResourceManager.GetString("PlaceholderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string PlaceholferConfirmPassword {
            get {
                return ResourceManager.GetString("PlaceholferConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - by date.
        /// </summary>
        public static string RButtonByDate {
            get {
                return ResourceManager.GetString("RButtonByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - by Name.
        /// </summary>
        public static string RButtonByName {
            get {
                return ResourceManager.GetString("RButtonByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - by Nick Name.
        /// </summary>
        public static string RButtonByNickName {
            get {
                return ResourceManager.GetString("RButtonByNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users SingIn.
        /// </summary>
        public static string SignInPageTitle {
            get {
                return ResourceManager.GetString("SignInPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users SingUp.
        /// </summary>
        public static string SignUpPageTitle {
            get {
                return ResourceManager.GetString("SignUpPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use camera.
        /// </summary>
        public static string UseCameraAlert {
            get {
                return ResourceManager.GetString("UseCameraAlert", resourceCulture);
            }
        }
    }
}
